#!/bin/bash

ubuntu() {
    package=$1
    echo "Ubuntu like:"
    echo -e "\tsudo apt install $package"
}

arch() {
    package=$1
    echo "Archlinux like:"
    echo -e "\tsudo pacman -S $package"
}

termux() {
    package=$1
    echo "Termux:"
    echo -e "\tpkg install $package"
}

if [[ "$NO_WHICH" == "ACTIVE" ]] || which 7z &> /dev/null; then
    if [[ "$NO_WHICH" == "ACTIVE" ]] || which cargo &> /dev/null; then
        cargo build --release
        if [[ "$NO_ELF_CLEANER" != "ACTIVE" ]] && uname --all | grep "Android" &> /dev/null; then
            echo "Termux detected."
            if [[ "$NO_WHICH" == "ACTIVE" ]] || which termux-elf-cleaner &> /dev/null; then
                echo "Cleaning elf header with termux-elf-cleaner."
                termux-elf-cleaner ./target/release/content-7z
            else
                echo "No termux-elf-cleaner found."
                echo "We use termux-elf-cleaner to clean the elf header, not being able to do so may cause problems in the correct execution of the program on some devices."
                termux "termux-elf-cleaner"
            fi
        fi

        if ! [ -z "${BIN}" ]; then
            cp ./target/release/content-7z $BIN &> /dev/null
        fi

        mkdir -p ~/.config/
        if ! [ -e "$HOME/.config/content-7z.toml" ]; then
            cp ./content-7z.toml $HOME/.config/content-7z.toml
        fi
    else
        echo "The rust command need to be installed."

        echo "Install it with your package manager:"
        ubuntu "rust"
        arch "rust"
        termux "rust"

        echo "Or in the official wiki:"
        echo -e "\x1b[4mhttps://www.rust-lang.org/es/tools/install\x1b[0m"
    fi
else
    echo "The 7z command need to be installed."

    echo "Install it with your package manager:"
    ubuntu "p7zip"
    arch "p7zip"
    termux "p7zip"

    echo "Or how you like to."
fi
